# Path configuration for automatic CI job triggering in GitHub Actions
# 
# This file defines which file changes should trigger workflows for each application.
# Used by check-changed-files.js to determine if jobs should run based on git diff.
#
# Structure:
# - common: shared paths that affect all applications (packages, configs, etc.)
# - intake: paths specific to Intake app + inherited common paths
# - ehr: paths specific to EHR app + inherited common paths
#
# Usage in workflows:
#   TRACKED_FILES=$(yq eval '.intake | join(" ")' .github/trigger-paths.yml)
#   node .github/check-changed-files.js $TRACKED_FILES

common: &common-paths
  - packages/zambdas/
  - packages/utils/
  - packages/ui-components/
  - .github/
  - .prettierignore
  - package.json

intake:
  - apps/intake/
  - *common-paths

ehr:
  - apps/ehr/
  - *common-paths
