name: Daily Tests
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches: ['984/automated-setup-script-testing']

env:
  PROJECT_ID: '5c29cd00-8df3-447b-aa49-2e65d262388c'
  NODE_VERSION: '18'
  NPM_VERSION: '9'
  TEST_EMAIL: 'gschneider@masslight.com'
  AUTH_URL: 'https://auth.zapehr.com/oauth/token'
  AUD_URL: 'https://api.zapehr.com'

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: testing
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm install -g npm@${{ env.NPM_VERSION }}

      - name: Get Access Token
        id: get-token
        run: |
          token=$(curl -s -X POST "${{ env.AUTH_URL }}" \
            -H "Content-Type: application/json" \
            -d '{
              "client_id": "${{ secrets.DAILY_TEST_M2M_CLIENT_ID }}",
              "client_secret": "${{ secrets.DAILY_TEST_M2M_CLIENT_SECRET }}",
              "audience": "${{ env.AUD_URL }}",
              "grant_type": "client_credentials"
            }' | jq -r '.access_token')
          echo "access_token=$token" >> $GITHUB_OUTPUT

      - name: Run setup script
        run: |
          chmod +x scripts/ottehr-setup.sh
          ./scripts/ottehr-setup.sh \
            "${{ env.PROJECT_ID }}" \
            "${{ steps.get-token.outputs.access_token }}" \
            "${{ env.TEST_EMAIL }}"

      - name: Run the cleanup script
        run: |
          npx ts-node scripts/ottehr-cleanup.ts \
            --"${{ env.PROJECT_ID }}" \
            --"${{ steps.get-token.outputs.access_token }}"
